services:
  - type: web
    name: stremio-vavoo-addon
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 3  # maxInstances deve essere maggiore di minInstances
      targetCPUPercent: 70  # Soglia di utilizzo della CPU per il bilanciamento
